Controllers/ActorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieHouse.Data;
using MovieHouse.Data.Services;
using MovieHouse.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieHouse.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorsService _service;
        public ActorsController(IActorsService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetActorsAsync(); 
            return View(data);
        }
        //Get: Actors/Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create([Bind("ProfilePictureURL, FirstName, LastName, Bio")] ActorModel actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.AddActorAsync(actor);
            return RedirectToAction(nameof(Index));
        }
        //Get: Actors/Delete/1
        public async Task<IActionResult> Delete(int Id)
        {
            var ActorDetails = await _service.GetActorByIdAsync(Id);
            if(ActorDetails == null)return View("Not Found");
            return View(ActorDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int Id)
        {
            var ActorDetails = await _service.GetActorByIdAsync(Id);
            if (ActorDetails == null) return View("Not Found");
            await _service.DeleteActorAsync(Id);
            return RedirectToAction(nameof(Index));
        }
        //Get: Actors/Details/1
        public async Task<IActionResult> Details(int Id)
        {
            var ActorDetails = await _service.GetActorByIdAsync(Id);
            if (ActorDetails == null) return View("Not Found");
            return View(ActorDetails);
        }
        //Get : Actors/Edit/1
        public async Task<IActionResult> Edit(int Id)
        {
            var ActorDetails = await _service.GetActorByIdAsync(Id);
            if (ActorDetails == null) return View("Not Found");
            return View(ActorDetails);
        }
        [HttpPost]
        public async Task<ActionResult> Edit(int Id, [Bind("Id, ProfilePictureURL, FirstName, LastName, Bio")] ActorModel actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.UpdateActorAsync(Id, actor);
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/CinemasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieHouse.Data;
using MovieHouse.Data.Services;
using MovieHouse.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieHouse.Controllers
{
    public class CinemasController : Controller
    {
        private readonly ICinemasService _service;
        public CinemasController(ICinemasService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetCinemas();
            return View(data);
        }
        //Get : Movies/Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create([Bind("Logo, Name, Description")] CinemaModel Cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(Cinema);
            }
            _service.AddCinema(Cinema);
            return RedirectToAction(nameof(Index));
        }
        //Get: Cinemas/Edit/1
        public async Task<IActionResult> Edit(int Id)
        {
            var CinemaDetails = await _service.GetCinemaByIdAsync(Id);
            if (CinemaDetails == null) return View("Not Found");
            return View(CinemaDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int Id, [Bind("Id, Logo, Name, Description")] CinemaModel Cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(Cinema);
            }
            await _service.UpdateCinemaAsync(Id, Cinema);
            return RedirectToAction(nameof(Index));
        }
        //Get : Cinemas/Delete/1
        public async Task<IActionResult> Delete(int Id)
        {
            var CinemaDetails = await _service.GetCinemaByIdAsync(Id);
            if (CinemaDetails == null) return View("Not Found");
            return View(CinemaDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int Id)
        {
            var DirectorDetails = await _service.GetCinemaByIdAsync(Id);
            if (DirectorDetails == null) return View("Not Found");
            await _service.DeleteCinemaAsync(Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/DirectorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieHouse.Data;
using MovieHouse.Data.Services;
using MovieHouse.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieHouse.Controllers
{
    public class DirectorsController : Controller
    {
        private readonly IDirectorsService _service;
        public DirectorsController(IDirectorsService service) => _service = service;
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetDirectors();
            return View(data);
        }

        //Get : Directors/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create([Bind("ProfilePictureURL, FirstName, LastName, Bio")] DirectorModel Director)
        {
            if (!ModelState.IsValid)
            {
                return View(Director);
            }
            _service.AddDirector(Director);
            return RedirectToAction(nameof(Index));
        }
        //Get : Directors/Edit/1
        public async Task<IActionResult> Edit(int Id)
        {
            var DirectorDetails = await _service.GetDirectorByIdAsync(Id);
            if (DirectorDetails == null) return View("Not Found");
            return View(DirectorDetails);
        }
        [HttpPost]
        public async Task<ActionResult> Edit(int Id, [Bind("Id, ProfilePictureURL, FirstName, LastName, Bio")] DirectorModel Director)
        {
            if (!ModelState.IsValid)
            {
                return View(Director);
            }
            await _service.UpdateDirectorAsync(Id, Director);
            return RedirectToAction(nameof(Index));
        }
        //Get : Directors/Details/1
        public async Task<IActionResult> Details(int Id)
        {
            var DirectorDetails = await _service.GetDirectorByIdAsync(Id);
            if (DirectorDetails == null) return View("Not Found");
            return View(DirectorDetails);
        }
        //Get : Directors/Delete/1
        public async Task<IActionResult> Delete(int Id)
        {
            var DirectorDetails = await _service.GetDirectorByIdAsync(Id);
            if (DirectorDetails == null) return View("Not Found");
            return View(DirectorDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int Id)
        {
            
            await _service.DeleteDirectorAsync(Id);
            return RedirectToAction(nameof(Index));
        }

    }
}

Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieHouse.Data;
using MovieHouse.Data.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieHouse.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMoviesService _service;
        public MoviesController(IMoviesService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetMovies();
            return View(data);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieHouse</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <script src="~/js/site.js" type="text/javascript"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-danger" asp-area="" asp-controller="Movies" asp-action="Index">MovieHouse</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="navbar-nav flex-grow-1">
                            <a class="nav-link text-light" asp-controller="Movies" asp-action="Index"><i class="badge-info bi-film"></i>Movies</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                            <i class="bi bi-gear">Management</i>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index"><i class="bi bi-camera-reels"></i>Cinemas</a>
                                <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"></i>Producers</a>
                                <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-square"></i>Actors</a>
                                <a class="dropdown-item" asp-controller="Directors" asp-action="Index"><i class="bi bi-person"></i>Directors</a>
                            </div>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0" asp-controller="Movies" asp-action="Filter" style="padding-right: 25px">
                        <input name="searchString" id="Search" type="text" class="form-control" placeholder="Search" />
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                     </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MovieHouse
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>