Controllers/ProducersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieHouse.Data;
using MovieHouse.Data.Services;
using MovieHouse.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieHouse.Controllers
{
    public class ProducersController : Controller
    {
        private readonly IProducersService _service;
        public ProducersController(IProducersService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetProducers();
            return View(data);
        }

        //Get: Producers/Create

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create([Bind("ProfilePictureURL, FirstName, LastName, Bio")] ProducerModel Producer)
        {
            if (!ModelState.IsValid)
            {
                return View(Producer);
            }
            _service.AddProducer(Producer);
            return RedirectToAction(nameof(Index));
        }
        //Get: Producers/Details/1
        public async Task<IActionResult> Details(int Id)
        {
            var ProducerDetails = await _service.GetProducerByIdAsync(Id);
            if (ProducerDetails == null) return View("Not Found");
            return View(ProducerDetails);
        }

        //Get: Producers/Delete/1
        public async Task<IActionResult> Delete(int Id)
        {
            var ProducerDetails = await _service.GetProducerByIdAsync(Id);
            if (ProducerDetails == null) return View("Not Found");
            return View(ProducerDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int Id)
        {
            var ProducerDetails = await _service.GetProducerByIdAsync(Id);
            if (ProducerDetails == null) return View("Not Found");
            await _service.DeleteProducerAsync(Id);
            return RedirectToAction(nameof(Index));
        }
        //Get : Producers/Edit/1
        public async Task<IActionResult> Edit(int Id)
        {
            var ProducerDetails = await _service.GetProducerByIdAsync(Id);
            if (ProducerDetails == null) return View("Not Found");
            return View(ProducerDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int Id, [Bind("Id, ProfilePictureURL, FirstName, LastName, Bio")] ProducerModel Producer)
        {
            if (!ModelState.IsValid) return View(Producer);
            await _service.UpdateProducerAsync(Id, Producer);
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Producers/Create.cshtml
@model ProducerModel
@{
    ViewData["Title"] = "Add a new Producer";
}


<div class="row">
    <div class="bg-light col-md-8 offset-2">
        <p>
            <h1 class="offset-3"><i class="bi bi-plus-circle"></i>Add a new Producer</h1>
        </p>
        <div class="offset-1 row bg-dark" style="max-width: 800px;">
            <div class="col-md-12">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <img id="ProfilePicturePreview" class="border border-10" style="max-height: 100px; max-width:100px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePictureURL" class="control-label text-white"></label>
                        <input asp-for="ProfilePictureURL" class="form-control" />
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label text-white"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label text-white"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                        <div class="form-group">
                            <label asp-for="Bio" class="control-label text-white"></label>
                            <input asp-for="Bio" class="form-control" />
                            <span asp-validation-for="Bio" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <button type="submit" value="Create" class="btn btn-success float-right">Create</button>
                            <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts
{
    <script>
        $(document).ready(function () {
            var Output = document.getElementById('ProfilePicturePreview');
            Output.src = $("#ProfilePictureURL").val();
        })
        $('#ProfilePictureURL').on('change', function () {
            var Output = document.getElementById('ProfilePicturePreview');
            Output.src = $(this).val();
        })
    </script>

}

Views/Producers/Delete.cshtml
@model ProducerModel
@{
    ViewData["Title"] = "Delete Producer";
}


<div class="row">
    <div class="bg-light col-md-8 offset-2">
        <p>
            <h1 class="offset-3"><i class="bi bi-trash-circle"></i>Delete @Model.FirstName @Model.LastName? </h1>
        </p>
        <div class="offset-1 row bg-dark" style="max-width: 800px;">
            <div class="col-md-12">
                <div class="form-group">
                    <img id="ProfilePicturePreview" class="border border-10" style="max-height: 100px; max-width:100px" />
                </div>
                <div class="form-group">
                    <label asp-for="ProfilePictureURL" class="control-label text-white"></label>
                    <input asp-for="ProfilePictureURL" class="form-control" readonly />
                    <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FirstName" class="control-label text-white"></label>
                    <input asp-for="FirstName" class="form-control" readonly />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastName" class="control-label text-white"></label>
                    <input asp-for="LastName" class="form-control" readonly />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Bio" class="control-label text-white"></label>
                    <input asp-for="Bio" class="form-control" />
                    <span asp-validation-for="Bio" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Confirm" class="btn btn-danger float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts
{
    <script>
        $(document).ready(function () {
            var Output = document.getElementById('ProfilePicturePreview');
            Output.src = $("#ProfilePictureURL").val();
        })
        $('#ProfilePictureURL').on('change', function () {
            var Output = document.getElementById('ProfilePicturePreview');
            Output.src = $(this).val();
        })
    </script>

}

Views/Producers/Details.cshtml
@model ProducerModel
@{
    ViewData["Title"] = "Details of this Producer";
}


<div class="row">
    <div class="bg-light col-md-8 offset-2">
        <p>
            <h1 class="offset-3"><i class="bi bi-plus-circle"></i>Details of @Model.FirstName @Model.LastName</h1>
        </p>
        <div class="offset-1 row bg-dark" style="max-width: 800px;">
            <div class="col-md-12">
                <div class="form-group">
                    <img id="ProfilePicturePreview" class="border border-10" style="max-height: 100px; max-width:100px" />
                </div>
                <div class="form-group">
                    <label asp-for="ProfilePictureURL" class="control-label text-white"></label>
                    <input asp-for="ProfilePictureURL" class="form-control" readonly />
                    <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FirstName" class="control-label text-white"></label>
                    <input asp-for="FirstName" class="form-control" readonly />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastName" class="control-label text-white"></label>
                    <input asp-for="LastName" class="form-control" readonly />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Bio" class="control-label text-white"></label>
                    <input asp-for="Bio" class="form-control" />
                    <span asp-validation-for="Bio" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <a class="btn btn-success float-right" asp-controller="Producers" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                    <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts
{
    <script>
        $(document).ready(function () {
            var Output = document.getElementById('ProfilePicturePreview');
            Output.src = $("#ProfilePictureURL").val();
        })
    </script>

}

Views/Producers/Edit.cshtml
@model ProducerModel
@{
    ViewData["Title"] = "Edit This Producer";
}


<div class="row">
    <div class="bg-light col-md-8 offset-2">
        <p>
            <h1 class="offset-3"><i class="bi bi-plus-circle"></i>Edit @Model.FirstName @Model.LastName</h1>
        </p>
        <div class="offset-1 row bg-dark" style="max-width: 800px;">
            <div class="col-md-12">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <img id="ProfilePicturePreview" class="border border-10" style="max-height: 100px; max-width:100px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePictureURL" class="control-label text-white"></label>
                        <input asp-for="ProfilePictureURL" class="form-control" />
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label text-white"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label text-white"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label text-white"></label>
                        <input asp-for="Bio" class="form-control" />
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <div class="form-group">
                            <input type="submit" value="Update" class="btn btn-success float-right" />
                            <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts
{
    <script>
        $(document).ready(function () {
            var Output = document.getElementById('ProfilePicturePreview');
            Output.src = $("#ProfilePictureURL").val();
        })
        $('#ProfilePictureURL').on('change', function () {
            var Output = document.getElementById('ProfilePicturePreview');
            Output.src = $(this).val();
        })
    </script>

}

Views/Producers/Index.cshtml
@model IEnumerable<ProducerModel>
@{
    ViewData["Title"] = "List of Producers";
}



<div class="container d-flex justify-content-center flex-column bg-transparent">
    <div class="row text-white d-flex justify-content-center p-2 border border-danger">
        <a asp-controller="Producers" asp-action="Create" class="btn btn-success float-lg-right"><i class="bi bi-plus-circle">Add New Producer</i></a>
    </div>
    <div class="row p-2 border border-success">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.ProfilePictureURL)</th>
                        <th>@Html.DisplayNameFor(model => model.FirstName)</th>
                        <th>@Html.DisplayNameFor(model => model.LastName)</th>
                        <th>@Html.DisplayNameFor(model => model.Bio)</th>
                        <th>Actions</th>
                        <th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" alt="@item.FirstName + @item.LastName" src="@item.ProfilePictureURL" style="max-width: 100px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.FirstName)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.LastName)
                        </td>
                        <td class="align-middle" style="max-width: 400px">
                            @Html.DisplayFor(modelItem => item.Bio)
                        </td>
                        <td class="align-middle">
                            <a class="btn btn-outline-primary" asp-controller="Producers" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit</a> |
                            <a class="btn btn-outline-info" asp-controller="Producers" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details</a> |
                            <a class="btn btn-danger text-white" asp-controller="Producers" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete</a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>